/**
 * Project Zomboid Sandbox Variables Schema
 * Defines categories, labels, tooltips, and validation rules for SandboxVars.lua.
 */

module.exports = {
    categories: {
        "Time": ["DayLength", "TimeSinceApo", "StartYear", "StartMonth", "StartDay", "StartTime"],
        "Zombie": [
            "Zombies", "Distribution", "ZombieVoronoiNoise", "ZombieRespawn", "ZombieMigrate",
            { section: "Zombie Lore" },
            "ZombieLore.Speed", "ZombieLore.SprinterPercentage", "ZombieLore.Strength", "ZombieLore.Toughness",
            "ZombieLore.Transmission", "ZombieLore.Mortality", "ZombieLore.Reanimate", "ZombieLore.Cognition",
            "ZombieLore.DoorOpeningPercentage", "ZombieLore.CrawlUnderVehicle", "ZombieLore.Memory",
            "ZombieLore.Sight", "ZombieLore.Hearing", "ZombieLore.SpottedLogic", "ZombieLore.ThumpNoChasing",
            "ZombieLore.ThumpOnConstruction", "ZombieLore.ActiveOnly", "ZombieLore.TriggerHouseAlarm",
            "ZombieLore.ZombiesDragDown", "ZombieLore.ZombiesCrawlersDragDown", "ZombieLore.ZombiesFenceLunge",
            "ZombieLore.DisableFakeDead", "ZombieLore.ZombiesArmorFactor", "ZombieLore.ZombiesMaxDefense",
            "ZombieLore.ChanceOfAttachedWeapon", "ZombieLore.ZombiesFallDamage", "ZombieLore.PlayerSpawnZombieRemoval",
            { section: "Advanced zombie settings" },
            "ZombieConfig.PopulationMultiplier", "ZombieConfig.PopulationStartMultiplier",
            "ZombieConfig.PopulationPeakMultiplier", "ZombieConfig.PopulationPeakDay",
            "ZombieConfig.RespawnHours", "ZombieConfig.RespawnUnseenHours", "ZombieConfig.RespawnMultiplier",
            "ZombieConfig.RedistributeHours", "ZombieConfig.FollowSoundDistance", "ZombieConfig.RallyGroupSize",
            "ZombieConfig.RallyGroupSizeVariance", "ZombieConfig.RallyTravelDistance",
            "ZombieConfig.RallyGroupSeparation", "ZombieConfig.RallyGroupRadius", "ZombieConfig.ZombiesCountBeforeDelete"
        ],
        "SandboxLoot": [
            "HoursForLootRespawn", "SeenHoursPreventLootRespawn", "MaxItemsForLootRespawn",
            "ConstructionPreventsLootRespawn", "MaximumLooted", "DaysUntilMaximumLooted",
            "RuralLooted", "MaximumDiminishedLoot", "DaysUntilMaximumDiminishedLoot",
            "MaximumLootedBuildingRooms",
            { section: "Loot Rarity" },
            "FoodLootNew", "CannedFoodLootNew", "WeaponLootNew", "RangedWeaponLootNew",
            "AmmoLootNew", "MedicalLootNew", "SurvivalGearsLootNew", "MechanicsLootNew",
            "SkillBookLoot", "RecipeResourceLoot", "LiteratureLootNew", "ClothingLootNew",
            "ContainerLootNew", "KeyLootNew", "MediaLootNew", "MementoLootNew",
            "CookwareLootNew", "MaterialLootNew", "FarmingLootNew", "ToolLootNew",
            "OtherLootNew", "GeneratorSpawning", "LootItemRemovalList", "RemoveStoryLoot",
            "RemoveZombieLoot", "RollsMultiplier", "ZombiePopLootEffect"
        ],
        "World": [
            "WaterShutModifier", "ElecShutModifier", "AlarmDecay", "Alarm", "LockedHouses",
            "FireSpread", "AllowExteriorGenerator", "GeneratorTileRange", "GeneratorVerticalPowerRange",
            "FuelStationGasInfinite", "FuelStationGasMin", "FuelStationGasMax", "FuelStationGasEmptyChance",
            "LightBulbLifespan", "FoodRotSpeed", "FridgeFactor", "DaysForRottenFoodRemoval",
            "WorldItemRemovalList", "HoursForWorldItemRemoval", "ItemRemovalListBlacklistToggle",
            { section: "Basements" },
            "Basement.SpawnFrequency", "MaximumFireFuelHours"
        ],
        "Nature": [
            "NightDarkness", "Temperature", "Rain", "MaxFogIntensity", "MaxRainFxIntensity",
            "ErosionSpeed", "ErosionDays", "FarmingSpeedNew", "CompostTime",
            "FishAbundance", "NatureAbundance", "PlantResilience", "FarmingAmountNew",
            "KillInsideCrops", "PlantGrowingSeasons", "PlaceDirtAboveground",
            "EnableSnowOnGround", "EnableTaintedWaterText", "MaximumRatIndex",
            "DaysUntilMaximumRatIndex", "ClayLakeChance", "ClayRiverChance"
        ],
        "Meta": [
            "Helicopter", "MetaEvent", "SleepingEvent", "GeneratorFuelConsumption",
            "SurvivorHouseChance", "VehicleStoryChance", "ZoneStoryChance", "AnnotatedMapChance",
            "HoursForCorpseRemoval", "DecayingCorpseHealthImpact", "ZombieHealthImpact",
            "BloodLevel", "BloodSplatLifespanDays", "MaggotSpawn", "MetaKnowledge",
            "DayNightCycle", "ClimateCycle", "FogCycle", "ZombieLore.FenceThumpersRequired", "ZombieLore.FenceDamageMultiplier",
            { section: "In-game Map" },
            "Map.AllowWorldMap", "Map.AllowMiniMap", "Map.MapAllKnown", "Map.MapNeedsLight"
        ],
        "Character": [
            "StatsDecrease", "EndRegen", "Nutrition", "StarterKit", "CharacterFreePoints",
            "ConstructionBonusPoints", "InjurySeverity", "BoneFracture", "MuscleStrainFactor",
            "DiscomfortFactor", "WoundInfectionFactor", "ClothingDegradation", "NoBlackClothes",
            "RearVulnerability", "MultiHitZombies", "FirearmUseDamageChance", "FirearmNoiseMultiplier",
            "FirearmJamMultiplier", "FirearmMoodleMultiplier", "FirearmWeatherMultiplier",
            "FirearmHeadGearEffect", "AttackBlockMovements", "AllClothesUnlocked", "EnablePoisoning",
            "LiteratureCooldown", "NegativeTraitsPenalty", "MinutesPerPage", "LevelForDismantleXPCutoff",
            "LevelForMediaXPCutoff", "EasyClimbing", "SeeNotLearntRecipe",
            { section: "XP multipliers" },
            "MultiplierConfig.Global", "MultiplierConfig.GlobalToggle",
            "MultiplierConfig.Fitness", "MultiplierConfig.Strength", "MultiplierConfig.Sprinting",
            "MultiplierConfig.Lightfoot", "MultiplierConfig.Nimble", "MultiplierConfig.Sneak",
            "MultiplierConfig.Axe", "MultiplierConfig.Blunt", "MultiplierConfig.SmallBlunt",
            "MultiplierConfig.LongBlade", "MultiplierConfig.SmallBlade", "MultiplierConfig.Spear",
            "MultiplierConfig.Maintenance", "MultiplierConfig.Farming", "MultiplierConfig.Husbandry",
            "MultiplierConfig.Woodwork", "MultiplierConfig.Carving", "MultiplierConfig.Cooking",
            "MultiplierConfig.Electricity", "MultiplierConfig.Doctor", "MultiplierConfig.FlintKnapping",
            "MultiplierConfig.Masonry", "MultiplierConfig.Mechanics", "MultiplierConfig.Blacksmith",
            "MultiplierConfig.Pottery", "MultiplierConfig.Tailoring", "MultiplierConfig.MetalWelding",
            "MultiplierConfig.Aiming", "MultiplierConfig.Reloading", "MultiplierConfig.Fishing",
            "MultiplierConfig.PlantScavenging", "MultiplierConfig.Tracking", "MultiplierConfig.Trapping",
            "MultiplierConfig.Butchering", "MultiplierConfig.Glassmaking"
        ],
        "SandboxVehicles": [
            "EnableVehicles", "VehicleEasyUse", "RecentlySurvivorVehicles", "ZombieAttractionMultiplier",
            "CarSpawnRate", "ChanceHasGas", "InitialGas", "CarGasConsumption", "LockedCar",
            "CarGeneralCondition", "TrafficJam", "CarAlarm", "PlayerDamageFromCrash",
            "CarDamageOnImpact", "SirenShutoffHours", "DamageToPlayerFromHitByACar", "SirenEffectsZombies"
        ],
        "Livestock": [
            "AnimalStatsModifier", "AnimalPregnancyTime", "AnimalEggHatch", "AnimalAgeModifier",
            "AnimalMilkIncModifier", "AnimalWoolIncModifier", "AnimalRanchChance",
            "AnimalGrassRegrowTime", "AnimalMetaPredator", "AnimalMatingSeason",
            "AnimalSoundAttractZombies", "AnimalTrackChance", "AnimalPathChance"
        ]
    },

    labelMap: {
        "DayLength": "Day Length (in real time)",
        "TimeSinceApo": "Months since the Apocalypse",
        "StartYear": "Start Year",
        "StartMonth": "Start Month",
        "StartDay": "Start Day",
        "StartTime": "Start Hour",
        "Zombies": "Zombie Count",
        "Distribution": "Zombie Distribution",
        "ZombieVoronoiNoise": "Voronoi Noise",
        "ZombieRespawn": "Zombie Respawn",
        "ZombieMigrate": "Zombie Migration",
        "ZombieLore.Speed": "Speed",
        "ZombieLore.SprinterPercentage": "Random Sprinter Amount",
        "ZombieLore.Strength": "Strength",
        "ZombieLore.Toughness": "Toughness",
        "ZombieLore.Transmission": "Transmission",
        "ZombieLore.Mortality": "Infection Mortality",
        "ZombieLore.Reanimate": "Reanimate Time",
        "ZombieLore.Cognition": "Cognition",
        "ZombieLore.DoorOpeningPercentage": "Random Door Opening Amount",
        "ZombieLore.CrawlUnderVehicle": "Crawl Under Vehicle",
        "ZombieLore.Memory": "Memory",
        "ZombieLore.Sight": "Sight",
        "ZombieLore.Hearing": "Hearing",
        "ZombieLore.SpottedLogic": "New Stealth System",
        "ZombieLore.ThumpNoChasing": "Environmental Attacks",
        "ZombieLore.ThumpOnConstruction": "Damage Construction",
        "ZombieLore.ActiveOnly": "Day/Night Zombie Speed Effect",
        "ZombieLore.TriggerHouseAlarm": "Zombie House Alarm Triggering",
        "ZombieLore.ZombiesDragDown": "Drag Down",
        "ZombieLore.ZombiesCrawlersDragDown": "Crawlers Drag Down",
        "ZombieLore.ZombiesFenceLunge": "Zombie Lunge",
        "ZombieLore.DisableFakeDead": "Fake Dead Zombie Reanimation",
        "ZombieLore.ZombiesArmorFactor": "Zombie Armor Factor",
        "ZombieLore.ZombiesMaxDefense": "Maximum Zombie Armor Defense",
        "ZombieLore.ChanceOfAttachedWeapon": "Chance Of Attached Weapon",
        "ZombieLore.ZombiesFallDamage": "Zombie Fall Damage Multiplier",
        "ZombieLore.PlayerSpawnZombieRemoval": "Player Spawn Area",
        "ZombieConfig.PopulationMultiplier": "Population Multiplier",
        "ZombieConfig.PopulationStartMultiplier": "Population Start Multiplier",
        "ZombieConfig.PopulationPeakMultiplier": "Population Peak Multiplier",
        "ZombieConfig.PopulationPeakDay": "Population Peak Day",
        "ZombieConfig.RespawnHours": "Respawn Hours",
        "ZombieConfig.RespawnUnseenHours": "Respawn Unseen Hours",
        "ZombieConfig.RespawnMultiplier": "Respawn Multiplier",
        "ZombieConfig.RedistributeHours": "Redistribute Hours",
        "ZombieConfig.FollowSoundDistance": "Follow Sound Distance",
        "ZombieConfig.RallyGroupSize": "Rally Group Size",
        "ZombieConfig.RallyGroupSizeVariance": "Rally Group Size Variance",
        "ZombieConfig.RallyTravelDistance": "Rally Travel Distance",
        "ZombieConfig.RallyGroupSeparation": "Rally Group Separation",
        "ZombieConfig.RallyGroupRadius": "Rally Group Radius",
        "ZombieConfig.ZombiesCountBeforeDelete": "Zombie count before deletion",
        "SeenHoursPreventLootRespawn": "Loot Seen Prevent Hours",
        "HoursForLootRespawn": "Hours for loot respawn",
        "MaxItemsForLootRespawn": "Max items for loot respawn",
        "ConstructionPreventsLootRespawn": "Construction prevents loot respawn",
        "MaximumLooted": "Maximum looted building chance",
        "DaysUntilMaximumLooted": "Days until maximum looted building chance",
        "RuralLooted": "Maximum rural looted building chance",
        "MaximumDiminishedLoot": "Maximum diminished loot percentage",
        "DaysUntilMaximumDiminishedLoot": "Days until maximum diminished loot percentage",
        "MaximumLootedBuildingRooms": "Maximum looted building rooms",
        "FoodLootNew": "Perishable Food",
        "CannedFoodLootNew": "Non-Perishable Food",
        "WeaponLootNew": "Melee Weapons",
        "RangedWeaponLootNew": "Ranged Weapons",
        "AmmoLootNew": "Ammo",
        "MedicalLootNew": "Medical",
        "SurvivalGearsLootNew": "Survival Essentials",
        "MechanicsLootNew": "Mechanics",
        "SkillBookLoot": "Skill Books",
        "RecipeResourceLoot": "Recipe Resources",
        "LiteratureLootNew": "Other Literature",
        "ClothingLootNew": "Clothing",
        "ContainerLootNew": "Bags",
        "KeyLootNew": "Keys",
        "MediaLootNew": "Media",
        "MementoLootNew": "Mementos",
        "CookwareLootNew": "Cooking",
        "MaterialLootNew": "Material",
        "FarmingLootNew": "Farming",
        "ToolLootNew": "Tools",
        "OtherLootNew": "Other",
        "GeneratorSpawning": "Generators",
        "LootItemRemovalList": "Loot Item Removal List",
        "RemoveStoryLoot": "Remove Unwanted Story Loot",
        "RemoveZombieLoot": "Remove Unwanted Zombie Loot",
        "RollsMultiplier": "Rolls Multiplier [!]",
        "ZombiePopLootEffect": "Zombie Population Loot Effect",
        "WaterShutModifier": "Water Shutoff",
        "ElecShutModifier": "Electricity Shutoff",
        "AlarmDecay": "Alarm Battery Decay",
        "Alarm": "House Alarms Frequency",
        "LockedHouses": "Locked Houses Frequency",
        "FireSpread": "Fire Spread",
        "AllowExteriorGenerator": "Generator Working in Exterior",
        "GeneratorTileRange": "Generator tile range",
        "GeneratorVerticalPowerRange": "Generator vertical range",
        "FuelStationGasInfinite": "Infinite Gas Pumps",
        "FuelStationGasMin": "Initial Minimum Gas Pump Amount",
        "FuelStationGasMax": "Initial Maximum Gas Pump Amount",
        "FuelStationGasEmptyChance": "Initial Gas Pump Empty Chance",
        "LightBulbLifespan": "Light Bulb Lifespan",
        "FoodRotSpeed": "Food Spoilage",
        "FridgeFactor": "Refrigeration Effectiveness",
        "DaysForRottenFoodRemoval": "Rotten Food Removal",
        "WorldItemRemovalList": "World Item Removal List",
        "HoursForWorldItemRemoval": "Hours for Removal List",
        "ItemRemovalListBlacklistToggle": "Removal List as Whitelist",
        "Basement.SpawnFrequency": "Basement Spawn Frequency",
        "MaximumFireFuelHours": "Maximum Fire Fuel Hours",
        "NightDarkness": "Darkness during night",
        "Temperature": "Temperature",
        "Rain": "Rain",
        "MaxFogIntensity": "Maximum Fog Intensity",
        "MaxRainFxIntensity": "Maximum Rain FX Intensity",
        "ErosionSpeed": "Erosion Speed",
        "ErosionDays": "Erosion Days",
        "FarmingSpeedNew": "Farming Speed",
        "CompostTime": "Compost Time",
        "FishAbundance": "Fishing Abundance",
        "NatureAbundance": "Nature's Abundance",
        "PlantResilience": "Plant Resilience",
        "FarmingAmountNew": "Farming Abundance",
        "KillInsideCrops": "Kill Crops Grown Inside",
        "PlantGrowingSeasons": "Plant Growing Seasons",
        "PlaceDirtAboveground": "Farms not on Ground Level [!]",
        "EnableSnowOnGround": "Snow on Ground",
        "EnableTaintedWaterText": "Enable 'Tainted Water' tooltip",
        "MaximumRatIndex": "Maximum Vermin Index",
        "DaysUntilMaximumRatIndex": "Days Until Maximum Vermin Index",
        "ClayLakeChance": "Clay chance - Lake",
        "ClayRiverChance": "Clay chance - River",
        "Helicopter": "Helicopter",
        "MetaEvent": "Meta Event",
        "SleepingEvent": "Sleeping Event",
        "GeneratorFuelConsumption": "Generator Fuel Consumption",
        "SurvivorHouseChance": "Randomized Building Chance",
        "VehicleStoryChance": "Randomized Road Stories Chance",
        "ZoneStoryChance": "Randomized Zone Stories Chance",
        "AnnotatedMapChance": "Annotated Map Chance",
        "HoursForCorpseRemoval": "Time Before Corpse Removal",
        "DecayingCorpseHealthImpact": "Decaying Corpse Health Impact",
        "ZombieHealthImpact": "Zombie Health Impact",
        "BloodLevel": "Blood Level",
        "BloodSplatLifespanDays": "Blood Splat Lifespan Days",
        "MaggotSpawn": "Corpse Maggot Spawn",
        "MetaKnowledge": "Media List Meta Knowledge",
        "DayNightCycle": "Day / Night Cycle",
        "ClimateCycle": "Climate Cycle",
        "FogCycle": "Fog Cycle",
        "ZombieLore.FenceThumpersRequired": "Zombies To Damage Fences",
        "ZombieLore.FenceDamageMultiplier": "Fence Damage Multiplier",
        "Map.AllowWorldMap": "Allow World Map",
        "Map.AllowMiniMap": "Allow Mini-Map",
        "Map.MapAllKnown": "All Known On Start",
        "Map.MapNeedsLight": "Light Needed To Read Map",
        "StatsDecrease": "Stats Decrease",
        "EndRegen": "Endurance Regeneration",
        "Nutrition": "Nutrition System",
        "StarterKit": "Starter Kit",
        "CharacterFreePoints": "Free Trait Points",
        "ConstructionBonusPoints": "Player-built Construction Strength",
        "InjurySeverity": "Injury Severity",
        "BoneFracture": "Bone Fracture",
        "MuscleStrainFactor": "Muscle Strain Factor",
        "DiscomfortFactor": "Discomfort Factor",
        "WoundInfectionFactor": "Wound Infection Damage Factor",
        "ClothingDegradation": "Clothing Degradation",
        "NoBlackClothes": "No Black Clothes",
        "RearVulnerability": "Rear Vulnerability",
        "MultiHitZombies": "Weapon Multi Hit",
        "FirearmUseDamageChance": "Firearms Use Damage Chance",
        "FirearmNoiseMultiplier": "Firearm Noise Multiplier",
        "FirearmJamMultiplier": "Firearm Jam Multiplier",
        "FirearmMoodleMultiplier": "Firearm Moodle Multiplier",
        "FirearmWeatherMultiplier": "Firearm Weather Multiplier",
        "FirearmHeadGearEffect": "Firearm Headgear Effect",
        "AttackBlockMovements": "Melee Movement Disruption",
        "AllClothesUnlocked": "All Clothing Unlocked",
        "EnablePoisoning": "Enable Poisoning",
        "LiteratureCooldown": "Literature Cooldown Days",
        "NegativeTraitsPenalty": "Negative Traits Penalty",
        "MinutesPerPage": "Minutes Per Skill Book Page",
        "LevelForDismantleXPCutoff": "Maximum Dismantling XP Level",
        "LevelForMediaXPCutoff": "Maximum Media XP Level",
        "EasyClimbing": "Easy Climbing",
        "SeeNotLearntRecipe": "See Not Known Recipes",
        "MultiplierConfig.Global": "Global Multiplier",
        "MultiplierConfig.GlobalToggle": "Use Global Multiplier",
        "MultiplierConfig.Fitness": "Fitness Multiplier",
        "MultiplierConfig.Strength": "Strength Multiplier",
        "MultiplierConfig.Sprinting": "Sprinting Multiplier",
        "MultiplierConfig.Lightfoot": "Lightfooted Multiplier",
        "MultiplierConfig.Nimble": "Nimble Multiplier",
        "MultiplierConfig.Sneak": "Sneaking Multiplier",
        "MultiplierConfig.Axe": "Axe Multiplier",
        "MultiplierConfig.Blunt": "Long Blunt Multiplier",
        "MultiplierConfig.SmallBlunt": "Short Blunt Multiplier",
        "MultiplierConfig.LongBlade": "Long Blade Multiplier",
        "MultiplierConfig.SmallBlade": "Short Blade Multiplier",
        "MultiplierConfig.Spear": "Spear Multiplier",
        "MultiplierConfig.Maintenance": "Maintenance Multiplier",
        "MultiplierConfig.Farming": "Agriculture Multiplier",
        "MultiplierConfig.Husbandry": "Animal Care Multiplier",
        "MultiplierConfig.Woodwork": "Carpentry Multiplier",
        "MultiplierConfig.Carving": "Carving Multiplier",
        "MultiplierConfig.Cooking": "Cooking Multiplier",
        "MultiplierConfig.Electricity": "Electrical Multiplier",
        "MultiplierConfig.Doctor": "First Aid Multiplier",
        "MultiplierConfig.FlintKnapping": "Knapping Multiplier",
        "MultiplierConfig.Masonry": "Masonry Multiplier",
        "MultiplierConfig.Mechanics": "Mechanics Multiplier",
        "MultiplierConfig.Blacksmith": "Blacksmithing Multiplier",
        "MultiplierConfig.Pottery": "Pottery",
        "MultiplierConfig.Tailoring": "Tailoring",
        "MultiplierConfig.MetalWelding": "Metalworking",
        "MultiplierConfig.Aiming": "Aiming",
        "MultiplierConfig.Reloading": "Reloading",
        "MultiplierConfig.Fishing": "Fishing",
        "MultiplierConfig.PlantScavenging": "Plant Scavenging",
        "MultiplierConfig.Tracking": "Tracking",
        "MultiplierConfig.Trapping": "Trapping",
        "MultiplierConfig.Butchering": "Butchering",
        "MultiplierConfig.Glassmaking": "Glassmaking",
        "EnableVehicles": "Vehicles",
        "VehicleEasyUse": "Easy Use",
        "RecentlySurvivorVehicles": "Recent Survivor Vehicles",
        "ZombieAttractionMultiplier": "Zombie Attraction Multiplier",
        "CarSpawnRate": "Vehicle Spawn Rate",
        "ChanceHasGas": "Chance Has Gas",
        "InitialGas": "Initial Gas",
        "CarGasConsumption": "Gas Consumption",
        "LockedCar": "Locked Vehicle Frequency",
        "CarGeneralCondition": "General Condition",
        "TrafficJam": "Car Wreck Congestion",
        "CarAlarm": "Vehicle Alarms Frequency",
        "PlayerDamageFromCrash": "Player Damage from Crash",
        "CarDamageOnImpact": "Car Damage on Impact",
        "SirenShutoffHours": "Siren Shutoff Hours",
        "DamageToPlayerFromHitByACar": "Player Damage From Vehicle Impact",
        "SirenEffectsZombies": "Vehicle Sirens Attract Zombies",
        "AnimalStatsModifier": "Stats Reduction Speed",
        "AnimalPregnancyTime": "Pregnancy Time",
        "AnimalEggHatch": "Egg Hatch Time",
        "AnimalAgeModifier": "Aging Modifier Speed",
        "AnimalMilkIncModifier": "Milk Increase Speed",
        "AnimalWoolIncModifier": "Wool Increase Speed",
        "AnimalRanchChance": "Animal Spawn Chance",
        "AnimalGrassRegrowTime": "Grass Regrow time",
        "AnimalMetaPredator": "Meta Predator",
        "AnimalMatingSeason": "Breeding Season",
        "AnimalSoundAttractZombies": "Animals Attract Zombies",
        "AnimalTrackChance": "Animal Tracks Chance",
        "AnimalPathChance": "Animal Paths Chance"
    },

    tooltipOverrides: {
        "DayLength": "Day Lenght (in real time):\nDefault = 1 Hour, 30 Minutes",
        "StartYear": "How long after the end of the world to begin.\nThis will affect starting world erosion and food spoilage.\nDoes not affect the starting date.\nDefault = 0",
        "StartMonth": "Month in which the game starts.\nDefault = July",
        "StartDay": "Day of the month in which the games starts.",
        "StartTime": "Hour of the day in which the game starts.\nDefault = 9 AM"
    },

    knownFloats: [
        "WoundInfectionFactor", "MuscleStrainFactor", "DiscomfortFactor",
        "MinutesPerPage", "FirearmNoiseMultiplier", "FirearmJamMultiplier",
        "FirearmMoodleMultiplier", "FirearmWeatherMultiplier",
        "FirearmUseDamageChance", "LightBulbLifespan", "FarmingSpeedNew", "FarmingAmountNew",
        "HoursForWorldItemRemoval", "FridgeFactor", "FoodRotSpeed",
        "ZombieAttractionMultiplier", "CarGasConsumption", "SirenShutoffHours",
        "FoodLootNew", "CannedFoodLootNew", "WeaponLootNew", "RangedWeaponLootNew",
        "AmmoLootNew", "MedicalLootNew", "SurvivalGearsLootNew", "MechanicsLootNew",
        "SkillBookLoot", "RecipeResourceLoot", "LiteratureLootNew", "ClothingLootNew",
        "ContainerLootNew", "KeyLootNew", "MediaLootNew", "MementoLootNew",
        "CookwareLootNew", "MaterialLootNew", "FarmingLootNew", "ToolLootNew",
        "OtherLootNew", "RollsMultiplier", "ZombiePopLootEffect",
        "MaximumDiminishedLoot", "MaximumLooted", "RuralLooted", "MaximumLootedBuildingRooms",
        "GeneratorFuelConsumption", "ZombieLore.FenceDamageMultiplier", "ZombieLore.ZombiesFallDamage",
        "ZombieLore.ZombiesArmorFactor", "ZombieLore.ZombiesMaxDefense", "MultiplierConfig.Global",
        "FirearmNoiseMultiplier", "FirearmJamMultiplier", "FirearmMoodleMultiplier", 
        "FirearmWeatherMultiplier", "FirearmUseDamageChance"
    ],

    fieldBlacklist: [
        "VERSION", "WaterShut", "ElecShut", "AlarmDecayModifier",
        "InsaneLootFactor", "ExtremeLootFactor", "RareLootFactor", "NormalLootFactor",
        "CommonLootFactor", "AbundantLootFactor", "Farming",
        "PlantAbundance", "NightLength", "AnimalMetaStatsModifier"
    ]
};
